APP: ""
capability:
  newCommandTimeout: 120
  launchTimeout: 120000
  platformVersion: ""
  platformName: "android"
  autoWebview: "false"
  autoLaunch: "true"
  noReset: "false"
androidCapability:
  deviceName: "android"
  appPackage: "com.fulihui.www.information"
#  appPackage: "com.cubic.autohome"
#  appActivity: ".SplashActivity"ormation"
  appActivity: ".SplashActivity"
  app: "E://Code//AppUiTest_V1.0//Driver//erduo.apk"
iosCapability:
  deviceName: "iPhone 6 Plus"
  bundleId: "com.xueqiu"
  screenshotWaitTimeout: "10"
  platformVersion: "9.3"
  autoAcceptAlerts: "true"
  app: ""
  appium: "http://127.0.0.1:4730/wd/hub"
